name: Build Python wheels

on:
  pull_request:
  push:
    branches: [main]
    tags:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15, macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_TEST_REQUIRES: pylint
          CIBW_TEST_COMMAND: python {project}/tests/test_all.py
          CIBW_TEST_COMMAND_WINDOWS: python.exe {project}/tests/test_all.py

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
